version: 1
disable_existing_loggers: false

formatters:
  verbose:
    "()": "app.ExtraLogFormatter"
    format: '%(levelname)s %(asctime)s %(filename)s:%(funcName)s:%(lineno)d %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    formatter: verbose
    stream: ext://sys.stdout

loggers:
  uvicorn:
    error:
      propagate: true

root:
  level: INFO
  handlers: [console]
  propagate: no
